[package]
name = "fullstack-entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backend = ["dep:async-trait", "dep:futures-util", "dep:tokio", "fullstack-entity-derive/backend"]
mongo = ["backend", "dep:mongodb", "fullstack-entity-derive/mongo"]

[dependencies]
fullstack-entity-derive = { path = "fullstack-entity-derive" }
serde = { version = "1.0.188", features = ["derive"] }
async-trait = { version = "0.1.73", optional = true }
futures-util = { version = "0.3.28", optional = true }
tokio = { version = "1.32.0", optional = true, features = ["sync"] }
mongodb = { version = "2.6.1", optional = true }