[package]
name = "live-entity-derive"
version = "0.0.1"
edition = "2021"

[dependencies]
syn = { version = "2.0.37", features = ["full"] }
quote = { version = "1.0.33" }
proc-macro2 = { version = "1.0.67" }

[lib]
proc-macro = true
